### ISSUE TITLE
ADD some Suggestions and codes to this repo

### ISSUE THREAD

**Issue by tomriddle77** [tomriddle77/hactober2021#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Amulya77** [comment]
I want to add a code as my first contribution in your Repository

**Comment by vibodh-jain** [comment]
I want to add a code to your repo.

**Comment by tomriddle77** [comment]
@vibodh-jain  you can add your code in my Public folder.

**Comment by vibodh-jain** [comment]
sure @tomriddle77  doing so
